import type { Document, Question } from './types';

// Realistic maritime document seed data
export const seedDocuments: Document[] = [
  {
    id: 'doc-001',
    filename: 'Safety_Manual_V12.pdf',
    originalName: 'Safety_Manual_V12.pdf',
    fileType: 'pdf',
    category: 'Safety',
    filePath: '/documents/safety-manual-v12.pdf',
    fileSize: 12500000,
    dateAdded: '2026-04-14T08:30:00Z',
    lastAccessed: '2026-04-15T10:00:00Z',
    pageCount: 245,
    textIndex: {
      documentId: 'doc-001',
      pages: [
        { pageNumber: 1, text: 'SAFETY MANAGEMENT SYSTEM MANUAL Version 12.0 - This manual provides comprehensive safety guidelines for vessel operations.' },
        { pageNumber: 14, text: 'Fire Safety Procedures: The emergency fire pump should be tested weekly. Starting the pump remotely from the bridge. Verifying suction and discharge pressure. Running for at least 10 minutes. The pump pressure must exceed 5.0 bar.' },
        { pageNumber: 23, text: 'Safety drill procedures must be conducted monthly. All crew members must participate in the safety drill exercises including fire fighting, abandon ship, and man overboard scenarios.' },
        { pageNumber: 45, text: 'Personal Protective Equipment (PPE) requirements for all deck operations include hard hats, safety shoes, gloves, and high visibility vests.' },
        { pageNumber: 78, text: 'Emergency response procedures for hazardous material spills. Immediate containment measures and notification protocols must be followed.' },
      ],
    },
  },
  {
    id: 'doc-002',
    filename: 'Navigation_Charts_Q3.pdf',
    originalName: 'Navigation_Charts_Q3.pdf',
    fileType: 'pdf',
    category: 'Navigation',
    filePath: '/documents/navigation-charts-q3.pdf',
    fileSize: 45100000,
    dateAdded: '2026-04-12T14:15:00Z',
    lastAccessed: '2026-04-14T16:00:00Z',
    pageCount: 180,
    textIndex: {
      documentId: 'doc-002',
      pages: [
        { pageNumber: 1, text: 'Navigation Charts and Passage Planning Guide - Quarter 3 2026. Covers Mediterranean Sea, Suez Canal approach, and Red Sea routing.' },
        { pageNumber: 15, text: 'Depth contours and bathymetric data for the Strait of Gibraltar. Minimum under-keel clearance must be maintained at all times during transit.' },
        { pageNumber: 34, text: 'Traffic Separation Scheme for the English Channel. All vessels must comply with COLREG Rule 10 requirements for traffic lanes.' },
        { pageNumber: 67, text: 'Weather routing considerations for North Atlantic crossings. Recommended seasonal routes to avoid heavy weather patterns.' },
      ],
    },
  },
  {
    id: 'doc-003',
    filename: 'Engine_Maintenance_Log.xlsx',
    originalName: 'Engine_Maintenance_Log.xlsx',
    fileType: 'xlsx',
    category: 'Engine',
    filePath: '/documents/engine-maintenance-log.xlsx',
    fileSize: 1300000,
    dateAdded: '2026-04-11T09:45:00Z',
    lastAccessed: '2026-04-13T11:30:00Z',
    pageCount: 12,
    textIndex: {
      documentId: 'doc-003',
      pages: [
        { pageNumber: 1, text: 'Main Engine Maintenance Log 2026. Scheduled maintenance records and pump pressure readings for all auxiliary systems.' },
        { pageNumber: 3, text: 'Verify the pump pressure remains within the recommended operating range of 5.5 to 8.0 bar. Record daily readings.' },
        { pageNumber: 5, text: 'Turbocharger inspection report. Blade condition satisfactory. Bearing clearances within tolerance. Next overhaul scheduled for dry dock.' },
        { pageNumber: 8, text: 'Auxiliary boiler maintenance: Check safety valves, inspect furnace, clean filters, test low water alarm and fuel pump pressure.' },
      ],
    },
  },
  {
    id: 'doc-004',
    filename: 'Cargo_Manifest_Voyage245.docx',
    originalName: 'Cargo_Manifest_Voyage245.docx',
    fileType: 'docx',
    category: 'Cargo',
    filePath: '/documents/cargo-manifest-voyage245.docx',
    fileSize: 2800000,
    dateAdded: '2026-04-10T16:20:00Z',
    lastAccessed: '2026-04-12T09:00:00Z',
    pageCount: 34,
    textIndex: {
      documentId: 'doc-004',
      pages: [
        { pageNumber: 1, text: 'CARGO MANIFEST - Voyage 245. Loading Port: Rotterdam. Discharge Port: Singapore. Total cargo: 28,500 MT.' },
        { pageNumber: 8, text: 'Dangerous goods declaration. IMDG Code Class 3 - Flammable Liquids. Proper stowage and segregation requirements.' },
        { pageNumber: 15, text: 'Cargo securing manual compliance. All containers lashed according to CSS code. Twist locks and turnbuckles inspected.' },
      ],
    },
  },
  {
    id: 'doc-005',
    filename: 'ISM_Code_Guidelines.pdf',
    originalName: 'ISM_Code_Guidelines.pdf',
    fileType: 'pdf',
    category: 'ISM',
    filePath: '/documents/ism-code-guidelines.pdf',
    fileSize: 18200000,
    dateAdded: '2026-04-08T11:00:00Z',
    lastAccessed: '2026-04-10T14:30:00Z',
    pageCount: 156,
    textIndex: {
      documentId: 'doc-005',
      pages: [
        { pageNumber: 1, text: 'International Safety Management Code Implementation Guide. This document provides guidance on establishing and maintaining a Safety Management System (SMS).' },
        { pageNumber: 12, text: 'Designated Person Ashore (DPA) responsibilities. The DPA shall have direct access to the highest level of management.' },
        { pageNumber: 28, text: 'Non-conformity reporting and corrective action procedures. All non-conformities must be documented and root cause analysis performed.' },
        { pageNumber: 45, text: 'Emergency preparedness and drill requirements. The company should establish procedures for potential emergency shipboard situations.' },
      ],
    },
  },
  {
    id: 'doc-006',
    filename: 'Fire_Safety_Procedures.pdf',
    originalName: 'Fire_Safety_Procedures.pdf',
    fileType: 'pdf',
    category: 'Safety',
    filePath: '/documents/fire-safety-procedures.pdf',
    fileSize: 8900000,
    dateAdded: '2026-04-15T06:00:00Z',
    lastAccessed: '2026-04-15T12:00:00Z',
    pageCount: 89,
    textIndex: {
      documentId: 'doc-006',
      pages: [
        { pageNumber: 1, text: 'FIRE SAFETY PROCEDURES AND EMERGENCY RESPONSE PLAN. This document outlines all fire fighting equipment, procedures, and drill requirements.' },
        { pageNumber: 12, text: 'What is the procedure for testing the emergency fire pump? The fire pump should be tested weekly. The procedure involves: 1. Starting the pump remotely from the bridge. 2. Verifying suction and discharge pressure. 3. Running for at least 10 minutes. The pressure must exceed 5.0 bar.' },
        { pageNumber: 23, text: 'Fire extinguisher inspection schedule. All portable fire extinguishers must be inspected monthly and pressure tested annually.' },
        { pageNumber: 34, text: 'Fixed fire fighting systems: CO2, foam, and water mist systems. Testing and maintenance schedules for each system type.' },
      ],
    },
  },
  {
    id: 'doc-007',
    filename: 'ECDIS_Operation_Manual.pdf',
    originalName: 'ECDIS_Operation_Manual.pdf',
    fileType: 'pdf',
    category: 'Navigation',
    filePath: '/documents/ecdis-operation-manual.pdf',
    fileSize: 15600000,
    dateAdded: '2026-04-14T10:00:00Z',
    lastAccessed: '2026-04-14T15:00:00Z',
    pageCount: 210,
    textIndex: {
      documentId: 'doc-007',
      pages: [
        { pageNumber: 1, text: 'ECDIS Operation Manual - Electronic Chart Display and Information System. Operational procedures and system configuration guide.' },
        { pageNumber: 25, text: 'Chart update procedures. ENC updates must be applied within 48 hours of receipt. Verify update application in system log.' },
        { pageNumber: 50, text: 'Route planning using ECDIS. Cross-track distance limits and waypoint approach alarms must be configured before departure.' },
      ],
    },
  },
  {
    id: 'doc-008',
    filename: 'Ballast_Water_Record_Book.xlsx',
    originalName: 'Ballast_Water_Record_Book.xlsx',
    fileType: 'xlsx',
    category: 'Cargo',
    filePath: '/documents/ballast-water-record.xlsx',
    fileSize: 980000,
    dateAdded: '2026-04-13T09:30:00Z',
    lastAccessed: '2026-04-14T08:00:00Z',
    pageCount: 8,
    textIndex: {
      documentId: 'doc-008',
      pages: [
        { pageNumber: 1, text: 'Ballast Water Record Book. In compliance with BWM Convention 2004. All ballast water operations must be recorded.' },
        { pageNumber: 3, text: 'Ballast exchange records. Mid-ocean exchange completed at position 35°N 045°W. Exchange efficiency verified through salinity testing.' },
      ],
    },
  },
  {
    id: 'doc-009',
    filename: 'Main_Engine_Service_Report.docx',
    originalName: 'Main_Engine_Service_Report.docx',
    fileType: 'docx',
    category: 'Engine',
    filePath: '/documents/main-engine-service-report.docx',
    fileSize: 4200000,
    dateAdded: '2026-04-09T13:15:00Z',
    lastAccessed: '2026-04-11T10:00:00Z',
    pageCount: 42,
    textIndex: {
      documentId: 'doc-009',
      pages: [
        { pageNumber: 1, text: 'Main Engine Service Report - Annual Overhaul 2026. MAN B&W 6S60MC-C engine. Service performed by authorized technicians.' },
        { pageNumber: 3, text: 'Checked auxiliary tube oil pump pressure, recorded at 4.2 bar. Within acceptable range. Fuel injection system tested satisfactory.' },
        { pageNumber: 15, text: 'Cylinder liner wear measurements. All liners within tolerance. Unit 3 approaching renewal limit, recommend monitoring.' },
        { pageNumber: 28, text: 'Crankshaft deflection readings recorded. All values within manufacturer specifications. No corrective action required.' },
      ],
    },
  },
  {
    id: 'doc-010',
    filename: 'Ship_Security_Plan.pdf',
    originalName: 'Ship_Security_Plan.pdf',
    fileType: 'pdf',
    category: 'ISPS',
    filePath: '/documents/ship-security-plan.pdf',
    fileSize: 6700000,
    dateAdded: '2026-04-07T08:00:00Z',
    lastAccessed: '2026-04-09T12:00:00Z',
    pageCount: 128,
    textIndex: {
      documentId: 'doc-010',
      pages: [
        { pageNumber: 1, text: 'SHIP SECURITY PLAN - Confidential. In compliance with ISPS Code and SOLAS Chapter XI-2. Security levels and response procedures.' },
        { pageNumber: 18, text: 'Security Level 1 - Normal operations. Access control procedures, cargo handling security, and monitoring requirements.' },
        { pageNumber: 35, text: 'Security Level 2 - Heightened threat. Enhanced access control, restricted areas, and additional monitoring measures.' },
        { pageNumber: 52, text: 'Security Level 3 - Exceptional threat. Emergency security procedures and coordination with port state authorities.' },
      ],
    },
  },
  {
    id: 'doc-011',
    filename: 'SIRE_VIQ_Checklist.pdf',
    originalName: 'SIRE_VIQ_Checklist.pdf',
    fileType: 'pdf',
    category: 'SIRE',
    filePath: '/documents/sire-viq-checklist.pdf',
    fileSize: 9800000,
    dateAdded: '2026-04-06T14:00:00Z',
    lastAccessed: '2026-04-08T16:00:00Z',
    pageCount: 312,
    textIndex: {
      documentId: 'doc-011',
      pages: [
        { pageNumber: 1, text: 'SIRE Vessel Inspection Questionnaire (VIQ) - 7th Edition. Comprehensive inspection checklist for tanker vessels.' },
        { pageNumber: 25, text: 'Chapter 3 - Certification and Documentation. Verification of statutory certificates and class documents.' },
        { pageNumber: 89, text: 'Chapter 7 - Cargo and Ballast Systems. Inspection of cargo pumps, valves, pipelines, and associated safety systems.' },
      ],
    },
  },
  {
    id: 'doc-012',
    filename: 'CDI_Inspection_Report.pdf',
    originalName: 'CDI_Inspection_Report.pdf',
    fileType: 'pdf',
    category: 'CDI',
    filePath: '/documents/cdi-inspection-report.pdf',
    fileSize: 5400000,
    dateAdded: '2026-04-05T10:30:00Z',
    lastAccessed: '2026-04-07T09:00:00Z',
    pageCount: 95,
    textIndex: {
      documentId: 'doc-012',
      pages: [
        { pageNumber: 1, text: 'Chemical Distribution Institute (CDI) Ship Inspection Report. Inspection conducted in accordance with CDI guidelines.' },
        { pageNumber: 12, text: 'Cargo handling operations review. Proper procedures for loading and discharging chemical cargoes verified.' },
        { pageNumber: 45, text: 'Tank cleaning procedures and verification. Inspection of tank coating condition and cleanliness standards.' },
      ],
    },
  },
];

// Realistic SIRE and CDI questions
export const seedQuestions: Question[] = [
  // SIRE Questions
  {
    id: 'q-sire-001',
    bankType: 'SIRE',
    questionNumber: '1.1',
    chapterSection: 'Chapter 1 - General Information',
    questionText: 'Is the vessel\'s Safety Management Certificate (SMC) valid and issued by an authorized organization?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-002',
    bankType: 'SIRE',
    questionNumber: '1.2',
    chapterSection: 'Chapter 1 - General Information',
    questionText: 'Is the Document of Compliance (DOC) for the company valid and available onboard?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-003',
    bankType: 'SIRE',
    questionNumber: '2.1',
    chapterSection: 'Chapter 2 - Certification and Documentation',
    questionText: 'Are all statutory certificates valid and are the vessel\'s class certificates maintained?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-004',
    bankType: 'SIRE',
    questionNumber: '3.1',
    chapterSection: 'Chapter 3 - Crew Management',
    questionText: 'Is the Master satisfied that the vessel is adequately manned for all operations?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-005',
    bankType: 'SIRE',
    questionNumber: '3.5',
    chapterSection: 'Chapter 3 - Crew Management',
    questionText: 'Are records of rest hours maintained and do they comply with STCW and MLC requirements?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-006',
    bankType: 'SIRE',
    questionNumber: '4.2',
    chapterSection: 'Chapter 4 - Navigation',
    questionText: 'Is the passage plan prepared berth to berth and approved by the Master?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-007',
    bankType: 'SIRE',
    questionNumber: '5.1',
    chapterSection: 'Chapter 5 - Safety Management',
    questionText: 'Are safety drills conducted at required intervals including fire-fighting, abandon ship, and man overboard?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-008',
    bankType: 'SIRE',
    questionNumber: '7.3',
    chapterSection: 'Chapter 7 - Cargo Operations',
    questionText: 'Are cargo pump room bilge alarms tested and operational, with records maintained?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-009',
    bankType: 'SIRE',
    questionNumber: '8.1',
    chapterSection: 'Chapter 8 - Mooring',
    questionText: 'Is a mooring plan available and does it comply with OCIMF guidelines?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-sire-010',
    bankType: 'SIRE',
    questionNumber: '9.2',
    chapterSection: 'Chapter 9 - Engine Room',
    questionText: 'Are all emergency generators tested weekly under load and are records maintained?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  // CDI Questions
  {
    id: 'q-cdi-001',
    bankType: 'CDI',
    questionNumber: 'A.1.1',
    chapterSection: 'Section A - General',
    questionText: 'Does the vessel have a valid Safety Management Certificate and Document of Compliance for the operating company?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-002',
    bankType: 'CDI',
    questionNumber: 'A.2.3',
    chapterSection: 'Section A - General',
    questionText: 'Are Material Safety Data Sheets (MSDS) available for all cargoes currently loaded or last three cargoes?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-003',
    bankType: 'CDI',
    questionNumber: 'B.1.1',
    chapterSection: 'Section B - Certification',
    questionText: 'Are all classification society certificates valid and are there any outstanding conditions of class?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-004',
    bankType: 'CDI',
    questionNumber: 'C.2.1',
    chapterSection: 'Section C - Crew',
    questionText: 'Are designated officers trained and certified in advanced chemical tanker operations?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-005',
    bankType: 'CDI',
    questionNumber: 'D.1.2',
    chapterSection: 'Section D - Navigation',
    questionText: 'Is the ECDIS operational and are Electronic Navigational Charts (ENCs) up to date?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-006',
    bankType: 'CDI',
    questionNumber: 'E.3.1',
    chapterSection: 'Section E - Cargo Operations',
    questionText: 'Are cargo tank atmosphere monitoring procedures established and are instruments calibrated?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-007',
    bankType: 'CDI',
    questionNumber: 'F.1.1',
    chapterSection: 'Section F - Safety',
    questionText: 'Are enclosed space entry procedures established, and are rescue and resuscitation equipment readily available?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
  {
    id: 'q-cdi-008',
    bankType: 'CDI',
    questionNumber: 'G.2.4',
    chapterSection: 'Section G - Pollution Prevention',
    questionText: 'Is the Shipboard Oil Pollution Emergency Plan (SOPEP) readily available and are crew members familiar with its contents?',
    dateAdded: '2026-04-01T00:00:00Z',
  },
];
